vota-prato/config/routes.rb
Rails.application.routes.draw do
  resources :comentarios

  resources :qualificacoes

  resources :clientes

	resources :restaurantes

end

vota-prato/app/models/comentario.rb
class Comentario < ActiveRecord::Base
	belongs_to :comentavel, polymorphic: true
end

vota-prato/app/controllers/comentarios_controller.rb
class ComentariosController < ApplicationController
  before_action :set_comentario, only: [:show, :edit, :update, :destroy]

  # GET /comentarios
  # GET /comentarios.json
  def index
    @comentarios = Comentario.all
  end

  # GET /comentarios/1
  # GET /comentarios/1.json
  def show
  end

  # GET /comentarios/new
  def new
    @comentario = Comentario.new
  end

  # GET /comentarios/1/edit
  def edit
  end

  # POST /comentarios
  # POST /comentarios.json
  def create
    @comentario = Comentario.new(comentario_params)

    respond_to do |format|
      if @comentario.save
        format.html { redirect_to @comentario, notice: 'Comentario was successfully created.' }
        format.json { render :show, status: :created, location: @comentario }
        format.js #ajax
      else
        format.html { render :new }
        format.json { render json: @comentario.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comentarios/1
  # PATCH/PUT /comentarios/1.json
  def update
    respond_to do |format|
      if @comentario.update(comentario_params)
        format.html { redirect_to @comentario, notice: 'Comentario was successfully updated.' }
        format.json { render :show, status: :ok, location: @comentario }
      else
        format.html { render :edit }
        format.json { render json: @comentario.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comentarios/1
  # DELETE /comentarios/1.json
  def destroy
    @comentario = Comentario.find(params[:id])
    @comentario.destroy

    respond_to do |format|
      format.html { redirect_to comentarios_url, notice: 'Comentario was successfully destroyed.' }
      format.json { head :no_content }
      #ajax
      format.js {head :ok}
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comentario
      @comentario = Comentario.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comentario_params
      params.require(:comentario).permit(:conteudo, :comentavel_id, :comentavel_type)
    end
end

vota-prato/app/helpers/comentarios_helper.rb
module ComentariosHelper
end

vota-prato/app/views/comentarios/_comentario.html.erb
<p id="comentario_<%= comentario.id %>">
	<%= comentario.conteudo %> - 
	<%= link_to '(remover)', comentario, method: :delete, remote: true, id: "remove_comentario_#{comentario.id}" %>
</p>

<% content_for :js do %>
	$('#remove_comentario_<%=comentario.id%>').bind('ajax:success', function(){ 
		$('#comentario_<%=comentario.id%>').remove();
		}
	);
<% end %>

vota-prato/app/views/comentarios/_comentarios.html.erb
<div id="comentarios">
	<h3>Comentários</h3>
	<% if comentarios.empty? %>
		Nenhum comentário
	<% else %>
		<%= render comentarios %>
	<% end %>
</div>

<% content_for :css do %>
	<link rel="stylesheet" href="/stylesheets/comentarios.css">
<% end %>

vota-prato/app/views/comentarios/_form.html.erb
<%= form_for(@comentario) do |f| %>
  <% if @comentario.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comentario.errors.count, "error") %> prohibited this comentario from being saved:</h2>

      <ul>
      <% @comentario.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :conteudo %><br>
    <%= f.text_area :conteudo %>
  </div>
  <div class="field">
    <%= f.label :comentavel_id %><br>
    <%= f.number_field :comentavel_id %>
  </div>
  <div class="field">
    <%= f.label :comentavel_type %><br>
    <%= f.text_field :comentavel_type %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

vota-prato/app/views/comentarios/_novo_comentario.html.erb
<%= form_for Comentario.new, remote: true do |f| %>
	<%= f.hidden_field :comentavel_id, value: comentavel.id %>
	<%= f.hidden_field :comentavel_type, value: comentavel.class %>

	<%= f.label :conteudo %><br/>
	<%= f.text_area :conteudo %>

	<%= f.submit %>
<% end %>

<% content_for :js do %>
	$('form').bind('ajax:complete', function(xhr, result){
		$('#comentarios').replaceWith(result.responseText);
		$('textarea').val("");
	});
<% end %>

vota-prato/app/views/comentarios/create.js.erb
<%= comentarios @comentario.comentavel %>

vota-prato/app/views/comentarios/edit.html.erb
<h1>Editing comentario</h1>

<%= render 'form' %>

<%= link_to 'Show', @comentario %> |
<%= link_to 'Back', comentarios_path %>

vota-prato/app/views/comentarios/index.html.erb
<h1>Listing comentarios</h1>

<table>
  <thead>
    <tr>
      <th>Conteudo</th>
      <th>Comentavel</th>
      <th>Comentavel type</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comentarios.each do |comentario| %>
      <tr>
        <td><%= comentario.conteudo %></td>
        <td><%= comentario.comentavel_id %></td>
        <td><%= comentario.comentavel_type %></td>
        <td><%= link_to 'Show', comentario %></td>
        <td><%= link_to 'Edit', edit_comentario_path(comentario) %></td>
        <td><%= link_to 'Destroy', comentario, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comentario', new_comentario_path %>

vota-prato/app/views/comentarios/new.html.erb
<h1>New comentario</h1>

<%= render 'form' %>

<%= link_to 'Back', comentarios_path %>

vota-prato/app/views/comentarios/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Conteudo:</strong>
  <%= @comentario.conteudo %>
</p>

<p>
  <strong>Comentavel:</strong>
  <%= @comentario.comentavel_id %>
</p>

<p>
  <strong>Comentavel type:</strong>
  <%= @comentario.comentavel_type %>
</p>

<%= link_to 'Edit', edit_comentario_path(@comentario) %> |
<%= link_to 'Back', comentarios_path %>